# This file contains configuration for the CfA@DTF blog
name: 2016 CfA DTF Fellowship
description: A small band of dedicated civic hackers making a difference to the way government works
avatar: https://codeforaustralia.github.io/DTF-Blog/images/CFA_FLogo.png

# Flags below are optional

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 2016-dtf-fellowship@codeforaustralia.org
  facebook:
  flickr:
  github: CodeforAustralia/DTF-Blog
  instagram:
  linkedin:
  pinterest:
  rss: rss # just type anything here for a working RSS icon
  twitter: CodeforAus
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

disqus: "cfv-dtf"
google_analytics: "UA-83515316-1"
url: "https://codeforaustralia.github.io/DTF-Blog"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/DTF-Blog"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
